# Generated from extern/softfloat/build/Linux-x86_64-GCC/Makefile (SoftFloat 3e,
# FAST_INT64 build, 8086-SSE specialisation). Regenerate if SoftFloat is re-pinned.
set(SOFTFLOAT_SOURCES
    ${SOFTFLOAT_DIR}/source/s_eq128.c
    ${SOFTFLOAT_DIR}/source/s_le128.c
    ${SOFTFLOAT_DIR}/source/s_lt128.c
    ${SOFTFLOAT_DIR}/source/s_shortShiftLeft128.c
    ${SOFTFLOAT_DIR}/source/s_shortShiftRight128.c
    ${SOFTFLOAT_DIR}/source/s_shortShiftRightJam64.c
    ${SOFTFLOAT_DIR}/source/s_shortShiftRightJam64Extra.c
    ${SOFTFLOAT_DIR}/source/s_shortShiftRightJam128.c
    ${SOFTFLOAT_DIR}/source/s_shortShiftRightJam128Extra.c
    ${SOFTFLOAT_DIR}/source/s_shiftRightJam32.c
    ${SOFTFLOAT_DIR}/source/s_shiftRightJam64.c
    ${SOFTFLOAT_DIR}/source/s_shiftRightJam64Extra.c
    ${SOFTFLOAT_DIR}/source/s_shiftRightJam128.c
    ${SOFTFLOAT_DIR}/source/s_shiftRightJam128Extra.c
    ${SOFTFLOAT_DIR}/source/s_shiftRightJam256M.c
    ${SOFTFLOAT_DIR}/source/s_countLeadingZeros8.c
    ${SOFTFLOAT_DIR}/source/s_countLeadingZeros16.c
    ${SOFTFLOAT_DIR}/source/s_countLeadingZeros32.c
    ${SOFTFLOAT_DIR}/source/s_countLeadingZeros64.c
    ${SOFTFLOAT_DIR}/source/s_add128.c
    ${SOFTFLOAT_DIR}/source/s_add256M.c
    ${SOFTFLOAT_DIR}/source/s_sub128.c
    ${SOFTFLOAT_DIR}/source/s_sub256M.c
    ${SOFTFLOAT_DIR}/source/s_mul64ByShifted32To128.c
    ${SOFTFLOAT_DIR}/source/s_mul64To128.c
    ${SOFTFLOAT_DIR}/source/s_mul128By32.c
    ${SOFTFLOAT_DIR}/source/s_mul128To256M.c
    ${SOFTFLOAT_DIR}/source/s_approxRecip_1Ks.c
    ${SOFTFLOAT_DIR}/source/s_approxRecip32_1.c
    ${SOFTFLOAT_DIR}/source/s_approxRecipSqrt_1Ks.c
    ${SOFTFLOAT_DIR}/source/s_approxRecipSqrt32_1.c
    ${SOFTFLOAT_DIR}/source/s_roundToUI32.c
    ${SOFTFLOAT_DIR}/source/s_roundToUI64.c
    ${SOFTFLOAT_DIR}/source/s_roundToI32.c
    ${SOFTFLOAT_DIR}/source/s_roundToI64.c
    ${SOFTFLOAT_DIR}/source/s_normSubnormalBF16Sig.c
    ${SOFTFLOAT_DIR}/source/s_roundPackToBF16.c
    ${SOFTFLOAT_DIR}/source/s_normSubnormalF16Sig.c
    ${SOFTFLOAT_DIR}/source/s_roundPackToF16.c
    ${SOFTFLOAT_DIR}/source/s_normRoundPackToF16.c
    ${SOFTFLOAT_DIR}/source/s_addMagsF16.c
    ${SOFTFLOAT_DIR}/source/s_subMagsF16.c
    ${SOFTFLOAT_DIR}/source/s_mulAddF16.c
    ${SOFTFLOAT_DIR}/source/s_normSubnormalF32Sig.c
    ${SOFTFLOAT_DIR}/source/s_roundPackToF32.c
    ${SOFTFLOAT_DIR}/source/s_normRoundPackToF32.c
    ${SOFTFLOAT_DIR}/source/s_addMagsF32.c
    ${SOFTFLOAT_DIR}/source/s_subMagsF32.c
    ${SOFTFLOAT_DIR}/source/s_mulAddF32.c
    ${SOFTFLOAT_DIR}/source/s_normSubnormalF64Sig.c
    ${SOFTFLOAT_DIR}/source/s_roundPackToF64.c
    ${SOFTFLOAT_DIR}/source/s_normRoundPackToF64.c
    ${SOFTFLOAT_DIR}/source/s_addMagsF64.c
    ${SOFTFLOAT_DIR}/source/s_subMagsF64.c
    ${SOFTFLOAT_DIR}/source/s_mulAddF64.c
    ${SOFTFLOAT_DIR}/source/s_normSubnormalExtF80Sig.c
    ${SOFTFLOAT_DIR}/source/s_roundPackToExtF80.c
    ${SOFTFLOAT_DIR}/source/s_normRoundPackToExtF80.c
    ${SOFTFLOAT_DIR}/source/s_addMagsExtF80.c
    ${SOFTFLOAT_DIR}/source/s_subMagsExtF80.c
    ${SOFTFLOAT_DIR}/source/s_normSubnormalF128Sig.c
    ${SOFTFLOAT_DIR}/source/s_roundPackToF128.c
    ${SOFTFLOAT_DIR}/source/s_normRoundPackToF128.c
    ${SOFTFLOAT_DIR}/source/s_addMagsF128.c
    ${SOFTFLOAT_DIR}/source/s_subMagsF128.c
    ${SOFTFLOAT_DIR}/source/s_mulAddF128.c
    ${SOFTFLOAT_DIR}/source/softfloat_state.c
    ${SOFTFLOAT_DIR}/source/ui32_to_f16.c
    ${SOFTFLOAT_DIR}/source/ui32_to_f32.c
    ${SOFTFLOAT_DIR}/source/ui32_to_f64.c
    ${SOFTFLOAT_DIR}/source/ui32_to_extF80.c
    ${SOFTFLOAT_DIR}/source/ui32_to_extF80M.c
    ${SOFTFLOAT_DIR}/source/ui32_to_f128.c
    ${SOFTFLOAT_DIR}/source/ui32_to_f128M.c
    ${SOFTFLOAT_DIR}/source/ui64_to_f16.c
    ${SOFTFLOAT_DIR}/source/ui64_to_f32.c
    ${SOFTFLOAT_DIR}/source/ui64_to_f64.c
    ${SOFTFLOAT_DIR}/source/ui64_to_extF80.c
    ${SOFTFLOAT_DIR}/source/ui64_to_extF80M.c
    ${SOFTFLOAT_DIR}/source/ui64_to_f128.c
    ${SOFTFLOAT_DIR}/source/ui64_to_f128M.c
    ${SOFTFLOAT_DIR}/source/i32_to_f16.c
    ${SOFTFLOAT_DIR}/source/i32_to_f32.c
    ${SOFTFLOAT_DIR}/source/i32_to_f64.c
    ${SOFTFLOAT_DIR}/source/i32_to_extF80.c
    ${SOFTFLOAT_DIR}/source/i32_to_extF80M.c
    ${SOFTFLOAT_DIR}/source/i32_to_f128.c
    ${SOFTFLOAT_DIR}/source/i32_to_f128M.c
    ${SOFTFLOAT_DIR}/source/i64_to_f16.c
    ${SOFTFLOAT_DIR}/source/i64_to_f32.c
    ${SOFTFLOAT_DIR}/source/i64_to_f64.c
    ${SOFTFLOAT_DIR}/source/i64_to_extF80.c
    ${SOFTFLOAT_DIR}/source/i64_to_extF80M.c
    ${SOFTFLOAT_DIR}/source/i64_to_f128.c
    ${SOFTFLOAT_DIR}/source/i64_to_f128M.c
    ${SOFTFLOAT_DIR}/source/bf16_isSignalingNaN.c
    ${SOFTFLOAT_DIR}/source/bf16_to_f32.c
    ${SOFTFLOAT_DIR}/source/f16_to_ui32.c
    ${SOFTFLOAT_DIR}/source/f16_to_ui64.c
    ${SOFTFLOAT_DIR}/source/f16_to_i32.c
    ${SOFTFLOAT_DIR}/source/f16_to_i64.c
    ${SOFTFLOAT_DIR}/source/f16_to_ui32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f16_to_ui64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f16_to_i32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f16_to_i64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f16_to_f32.c
    ${SOFTFLOAT_DIR}/source/f16_to_f64.c
    ${SOFTFLOAT_DIR}/source/f16_to_extF80.c
    ${SOFTFLOAT_DIR}/source/f16_to_extF80M.c
    ${SOFTFLOAT_DIR}/source/f16_to_f128.c
    ${SOFTFLOAT_DIR}/source/f16_to_f128M.c
    ${SOFTFLOAT_DIR}/source/f16_roundToInt.c
    ${SOFTFLOAT_DIR}/source/f16_add.c
    ${SOFTFLOAT_DIR}/source/f16_sub.c
    ${SOFTFLOAT_DIR}/source/f16_mul.c
    ${SOFTFLOAT_DIR}/source/f16_mulAdd.c
    ${SOFTFLOAT_DIR}/source/f16_div.c
    ${SOFTFLOAT_DIR}/source/f16_rem.c
    ${SOFTFLOAT_DIR}/source/f16_sqrt.c
    ${SOFTFLOAT_DIR}/source/f16_eq.c
    ${SOFTFLOAT_DIR}/source/f16_le.c
    ${SOFTFLOAT_DIR}/source/f16_lt.c
    ${SOFTFLOAT_DIR}/source/f16_eq_signaling.c
    ${SOFTFLOAT_DIR}/source/f16_le_quiet.c
    ${SOFTFLOAT_DIR}/source/f16_lt_quiet.c
    ${SOFTFLOAT_DIR}/source/f16_isSignalingNaN.c
    ${SOFTFLOAT_DIR}/source/f32_to_ui32.c
    ${SOFTFLOAT_DIR}/source/f32_to_ui64.c
    ${SOFTFLOAT_DIR}/source/f32_to_i32.c
    ${SOFTFLOAT_DIR}/source/f32_to_i64.c
    ${SOFTFLOAT_DIR}/source/f32_to_ui32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f32_to_ui64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f32_to_i32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f32_to_i64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f32_to_bf16.c
    ${SOFTFLOAT_DIR}/source/f32_to_f16.c
    ${SOFTFLOAT_DIR}/source/f32_to_f64.c
    ${SOFTFLOAT_DIR}/source/f32_to_extF80.c
    ${SOFTFLOAT_DIR}/source/f32_to_extF80M.c
    ${SOFTFLOAT_DIR}/source/f32_to_f128.c
    ${SOFTFLOAT_DIR}/source/f32_to_f128M.c
    ${SOFTFLOAT_DIR}/source/f32_roundToInt.c
    ${SOFTFLOAT_DIR}/source/f32_add.c
    ${SOFTFLOAT_DIR}/source/f32_sub.c
    ${SOFTFLOAT_DIR}/source/f32_mul.c
    ${SOFTFLOAT_DIR}/source/f32_mulAdd.c
    ${SOFTFLOAT_DIR}/source/f32_div.c
    ${SOFTFLOAT_DIR}/source/f32_rem.c
    ${SOFTFLOAT_DIR}/source/f32_sqrt.c
    ${SOFTFLOAT_DIR}/source/f32_eq.c
    ${SOFTFLOAT_DIR}/source/f32_le.c
    ${SOFTFLOAT_DIR}/source/f32_lt.c
    ${SOFTFLOAT_DIR}/source/f32_eq_signaling.c
    ${SOFTFLOAT_DIR}/source/f32_le_quiet.c
    ${SOFTFLOAT_DIR}/source/f32_lt_quiet.c
    ${SOFTFLOAT_DIR}/source/f32_isSignalingNaN.c
    ${SOFTFLOAT_DIR}/source/f64_to_ui32.c
    ${SOFTFLOAT_DIR}/source/f64_to_ui64.c
    ${SOFTFLOAT_DIR}/source/f64_to_i32.c
    ${SOFTFLOAT_DIR}/source/f64_to_i64.c
    ${SOFTFLOAT_DIR}/source/f64_to_ui32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f64_to_ui64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f64_to_i32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f64_to_i64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f64_to_f16.c
    ${SOFTFLOAT_DIR}/source/f64_to_f32.c
    ${SOFTFLOAT_DIR}/source/f64_to_extF80.c
    ${SOFTFLOAT_DIR}/source/f64_to_extF80M.c
    ${SOFTFLOAT_DIR}/source/f64_to_f128.c
    ${SOFTFLOAT_DIR}/source/f64_to_f128M.c
    ${SOFTFLOAT_DIR}/source/f64_roundToInt.c
    ${SOFTFLOAT_DIR}/source/f64_add.c
    ${SOFTFLOAT_DIR}/source/f64_sub.c
    ${SOFTFLOAT_DIR}/source/f64_mul.c
    ${SOFTFLOAT_DIR}/source/f64_mulAdd.c
    ${SOFTFLOAT_DIR}/source/f64_div.c
    ${SOFTFLOAT_DIR}/source/f64_rem.c
    ${SOFTFLOAT_DIR}/source/f64_sqrt.c
    ${SOFTFLOAT_DIR}/source/f64_eq.c
    ${SOFTFLOAT_DIR}/source/f64_le.c
    ${SOFTFLOAT_DIR}/source/f64_lt.c
    ${SOFTFLOAT_DIR}/source/f64_eq_signaling.c
    ${SOFTFLOAT_DIR}/source/f64_le_quiet.c
    ${SOFTFLOAT_DIR}/source/f64_lt_quiet.c
    ${SOFTFLOAT_DIR}/source/f64_isSignalingNaN.c
    ${SOFTFLOAT_DIR}/source/extF80_to_ui32.c
    ${SOFTFLOAT_DIR}/source/extF80_to_ui64.c
    ${SOFTFLOAT_DIR}/source/extF80_to_i32.c
    ${SOFTFLOAT_DIR}/source/extF80_to_i64.c
    ${SOFTFLOAT_DIR}/source/extF80_to_ui32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/extF80_to_ui64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/extF80_to_i32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/extF80_to_i64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/extF80_to_f16.c
    ${SOFTFLOAT_DIR}/source/extF80_to_f32.c
    ${SOFTFLOAT_DIR}/source/extF80_to_f64.c
    ${SOFTFLOAT_DIR}/source/extF80_to_f128.c
    ${SOFTFLOAT_DIR}/source/extF80_roundToInt.c
    ${SOFTFLOAT_DIR}/source/extF80_add.c
    ${SOFTFLOAT_DIR}/source/extF80_sub.c
    ${SOFTFLOAT_DIR}/source/extF80_mul.c
    ${SOFTFLOAT_DIR}/source/extF80_div.c
    ${SOFTFLOAT_DIR}/source/extF80_rem.c
    ${SOFTFLOAT_DIR}/source/extF80_sqrt.c
    ${SOFTFLOAT_DIR}/source/extF80_eq.c
    ${SOFTFLOAT_DIR}/source/extF80_le.c
    ${SOFTFLOAT_DIR}/source/extF80_lt.c
    ${SOFTFLOAT_DIR}/source/extF80_eq_signaling.c
    ${SOFTFLOAT_DIR}/source/extF80_le_quiet.c
    ${SOFTFLOAT_DIR}/source/extF80_lt_quiet.c
    ${SOFTFLOAT_DIR}/source/extF80_isSignalingNaN.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_ui32.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_ui64.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_i32.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_i64.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_ui32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_ui64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_i32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_i64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_f16.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_f32.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_f64.c
    ${SOFTFLOAT_DIR}/source/extF80M_to_f128M.c
    ${SOFTFLOAT_DIR}/source/extF80M_roundToInt.c
    ${SOFTFLOAT_DIR}/source/extF80M_add.c
    ${SOFTFLOAT_DIR}/source/extF80M_sub.c
    ${SOFTFLOAT_DIR}/source/extF80M_mul.c
    ${SOFTFLOAT_DIR}/source/extF80M_div.c
    ${SOFTFLOAT_DIR}/source/extF80M_rem.c
    ${SOFTFLOAT_DIR}/source/extF80M_sqrt.c
    ${SOFTFLOAT_DIR}/source/extF80M_eq.c
    ${SOFTFLOAT_DIR}/source/extF80M_le.c
    ${SOFTFLOAT_DIR}/source/extF80M_lt.c
    ${SOFTFLOAT_DIR}/source/extF80M_eq_signaling.c
    ${SOFTFLOAT_DIR}/source/extF80M_le_quiet.c
    ${SOFTFLOAT_DIR}/source/extF80M_lt_quiet.c
    ${SOFTFLOAT_DIR}/source/f128_to_ui32.c
    ${SOFTFLOAT_DIR}/source/f128_to_ui64.c
    ${SOFTFLOAT_DIR}/source/f128_to_i32.c
    ${SOFTFLOAT_DIR}/source/f128_to_i64.c
    ${SOFTFLOAT_DIR}/source/f128_to_ui32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f128_to_ui64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f128_to_i32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f128_to_i64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f128_to_f16.c
    ${SOFTFLOAT_DIR}/source/f128_to_f32.c
    ${SOFTFLOAT_DIR}/source/f128_to_extF80.c
    ${SOFTFLOAT_DIR}/source/f128_to_f64.c
    ${SOFTFLOAT_DIR}/source/f128_roundToInt.c
    ${SOFTFLOAT_DIR}/source/f128_add.c
    ${SOFTFLOAT_DIR}/source/f128_sub.c
    ${SOFTFLOAT_DIR}/source/f128_mul.c
    ${SOFTFLOAT_DIR}/source/f128_mulAdd.c
    ${SOFTFLOAT_DIR}/source/f128_div.c
    ${SOFTFLOAT_DIR}/source/f128_rem.c
    ${SOFTFLOAT_DIR}/source/f128_sqrt.c
    ${SOFTFLOAT_DIR}/source/f128_eq.c
    ${SOFTFLOAT_DIR}/source/f128_le.c
    ${SOFTFLOAT_DIR}/source/f128_lt.c
    ${SOFTFLOAT_DIR}/source/f128_eq_signaling.c
    ${SOFTFLOAT_DIR}/source/f128_le_quiet.c
    ${SOFTFLOAT_DIR}/source/f128_lt_quiet.c
    ${SOFTFLOAT_DIR}/source/f128_isSignalingNaN.c
    ${SOFTFLOAT_DIR}/source/f128M_to_ui32.c
    ${SOFTFLOAT_DIR}/source/f128M_to_ui64.c
    ${SOFTFLOAT_DIR}/source/f128M_to_i32.c
    ${SOFTFLOAT_DIR}/source/f128M_to_i64.c
    ${SOFTFLOAT_DIR}/source/f128M_to_ui32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f128M_to_ui64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f128M_to_i32_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f128M_to_i64_r_minMag.c
    ${SOFTFLOAT_DIR}/source/f128M_to_f16.c
    ${SOFTFLOAT_DIR}/source/f128M_to_f32.c
    ${SOFTFLOAT_DIR}/source/f128M_to_extF80M.c
    ${SOFTFLOAT_DIR}/source/f128M_to_f64.c
    ${SOFTFLOAT_DIR}/source/f128M_roundToInt.c
    ${SOFTFLOAT_DIR}/source/f128M_add.c
    ${SOFTFLOAT_DIR}/source/f128M_sub.c
    ${SOFTFLOAT_DIR}/source/f128M_mul.c
    ${SOFTFLOAT_DIR}/source/f128M_mulAdd.c
    ${SOFTFLOAT_DIR}/source/f128M_div.c
    ${SOFTFLOAT_DIR}/source/f128M_rem.c
    ${SOFTFLOAT_DIR}/source/f128M_sqrt.c
    ${SOFTFLOAT_DIR}/source/f128M_eq.c
    ${SOFTFLOAT_DIR}/source/f128M_le.c
    ${SOFTFLOAT_DIR}/source/f128M_lt.c
    ${SOFTFLOAT_DIR}/source/f128M_eq_signaling.c
    ${SOFTFLOAT_DIR}/source/f128M_le_quiet.c
    ${SOFTFLOAT_DIR}/source/f128M_lt_quiet.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/softfloat_raiseFlags.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_f16UIToCommonNaN.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_commonNaNToF16UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_propagateNaNF16UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_bf16UIToCommonNaN.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_commonNaNToBF16UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_f32UIToCommonNaN.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_commonNaNToF32UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_propagateNaNF32UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_f64UIToCommonNaN.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_commonNaNToF64UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_propagateNaNF64UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/extF80M_isSignalingNaN.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_extF80UIToCommonNaN.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_commonNaNToExtF80UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_propagateNaNExtF80UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/f128M_isSignalingNaN.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_f128UIToCommonNaN.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_commonNaNToF128UI.c
    ${SOFTFLOAT_DIR}/source/8086-SSE/s_propagateNaNF128UI.c
)
